name: Patch and Publish

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: "Version bump type"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write
  packages: write

jobs:
  patch-and-publish:
    name: Patch and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build

      - name: Configure Git
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git config --local url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Get current version
        id: current_version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Bump version
        id: version_bump
        run: |
          echo "Current version: $(node -p "require('./package.json').version")"
          NEW_VERSION=$(npm version ${{ github.event.inputs.version_type }} --no-git-tag-version)
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "Bumped version from ${{ steps.current_version.outputs.version }} to $NEW_VERSION"
          echo "New version is: $NEW_VERSION"

      - name: Generate changelog
        run: |
          # Create temporary changelog for new version
          echo "## ${{ steps.version_bump.outputs.new_version }} - $(date +'%Y-%m-%d')" > CHANGELOG_NEW.md
          echo "" >> CHANGELOG_NEW.md
          echo "### Changes" >> CHANGELOG_NEW.md

          # Get commits since last tag or from beginning if no tags
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          if [ -z "$LAST_TAG" ]; then
            echo "- Initial release" >> CHANGELOG_NEW.md
            git log --pretty=format:"- %s" --no-merges >> CHANGELOG_NEW.md
          else
            git log $LAST_TAG..HEAD --pretty=format:"- %s" --no-merges >> CHANGELOG_NEW.md
          fi

          echo "" >> CHANGELOG_NEW.md
          echo "" >> CHANGELOG_NEW.md

          # If existing changelog exists, merge with new entry at the top
          if [ -f CHANGELOG.md ]; then
            # Create new changelog with new version at top
            echo "# Changelog" > CHANGELOG_TEMP.md
            echo "" >> CHANGELOG_TEMP.md
            cat CHANGELOG_NEW.md >> CHANGELOG_TEMP.md
            # Skip the first two lines (# Changelog and empty line) from existing changelog
            tail -n +3 CHANGELOG.md >> CHANGELOG_TEMP.md
            mv CHANGELOG_TEMP.md CHANGELOG.md
          else
            # Create new changelog file
            echo "# Changelog" > CHANGELOG.md
            echo "" >> CHANGELOG.md
            cat CHANGELOG_NEW.md >> CHANGELOG.md
          fi

          # Clean up temporary file
          rm -f CHANGELOG_NEW.md

      - name: Commit version bump and changelog
        run: |
          git add package.json package-lock.json CHANGELOG.md
          git commit -m "chore: bump version to ${{ steps.version_bump.outputs.new_version }} and update changelog"

      - name: Create Git tag
        run: |
          git tag ${{ steps.version_bump.outputs.new_version }}

      - name: Push changes and tags
        run: |
          echo "Pushing changes to main branch..."
          git push origin main
          echo "Creating and pushing tag ${{ steps.version_bump.outputs.new_version }}..."
          git push origin ${{ steps.version_bump.outputs.new_version }}
          echo "Successfully pushed changes and tags!"

      - name: Publish to npm
        run: |
          echo "Publishing to npm..."
          npm publish --access public
          echo "Successfully published to npm!"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        run: |
          gh release create ${{ steps.version_bump.outputs.new_version }} \
            --title "Release ${{ steps.version_bump.outputs.new_version }}" \
            --notes "## Changes in ${{ steps.version_bump.outputs.new_version }}

          See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for detailed changes.

          ### Installation
          \`\`\`bash
          npm install @gthangaraj-fr/react-button-library@${{ steps.version_bump.outputs.new_version }}
          \`\`\`"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Notify Slack
      #   run: |
      #     curl -X POST -H 'Content-type: application/json' \
      #       --data '{
      #         "text": ":rocket: New version published!",
      #         "blocks": [
      #           {
      #             "type": "header",
      #             "text": {
      #               "type": "plain_text",
      #               "text": ":package: React Button Library v${{ steps.version_bump.outputs.new_version }} Published!"
      #             }
      #           },
      #           {
      #             "type": "section",
      #             "text": {
      #               "type": "mrkdwn",
      #               "text": "A new version of the React Button Library has been successfully published to npm! :tada:"
      #             }
      #           },
      #           {
      #             "type": "section",
      #             "fields": [
      #               {
      #                 "type": "mrkdwn",
      #                 "text": "*Version:*\n`${{ steps.version_bump.outputs.new_version }}`"
      #               },
      #               {
      #                 "type": "mrkdwn",
      #                 "text": "*Package:*\n`@gthangaraj-fr/react-button-library`"
      #               }
      #             ]
      #           },
      #           {
      #             "type": "section",
      #             "text": {
      #               "type": "mrkdwn",
      #               "text": "*Install the new version:*\n```npm install @gthangaraj-fr/react-button-library@${{ steps.version_bump.outputs.new_version }}```"
      #             }
      #           },
      #           {
      #             "type": "actions",
      #             "elements": [
      #               {
      #                 "type": "button",
      #                 "text": {
      #                   "type": "plain_text",
      #                   "text": "View Changelog"
      #                 },
      #                 "url": "https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md",
      #                 "style": "primary"
      #               },
      #               {
      #                 "type": "button",
      #                 "text": {
      #                   "type": "plain_text",
      #                   "text": "View Release"
      #                 },
      #                 "url": "https://github.com/${{ github.repository }}/releases/tag/${{ steps.version_bump.outputs.new_version }}"
      #               },
      #               {
      #                 "type": "button",
      #                 "text": {
      #                   "type": "plain_text",
      #                   "text": "npm Package"
      #                 },
      #                 "url": "https://www.npmjs.com/package/@gthangaraj-fr/react-button-library"
      #               }
      #             ]
      #           }
      #         ]
      #       }' \
      #       ${{ secrets.SLACK_WEBHOOK_URL }}
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
